# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!

target 'uPortMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for uPortMobile
  source 'https://github.com/CocoaPods/Specs.git'

  pod 'AWSCore'
  pod 'AWSSNS'
  pod 'AWSCognito'
  pod 'AWSCognito'
  pod 'Valet'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Promises'
  pod 'XyBleSdk', :path => '../XYO/XYObleInterface/'
  pod 'mod-ble-swift', :path => '../XYO/sdk-ble-swift/'
  pod 'sdk-objectmodel-swift', '~> 0.1.2-beta.0'
  pod 'sdk-core-swift', '~> 0.1.2-beta.2'
  
  target 'uPortMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
